site_name: UEG Wiki
site_description: UEG Wiki
site_author: United Earth

theme:
  name: "material"
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  font:
    text: Noto Sans
    code: Source Code Pro

extra:
  alternate:
    - link: /
      name: zh_cn - 简体中文
  copyright: CC BY-NC-SA 4.0
extra_javascript:
  - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
  - static/js/custom.css
  - https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - static/css/custom.css

nav:
  - 天文学:
      - 太阳:
          - sun/index.md
          - sun/heliumflash.md
          - sun/solarcrisis.md
          - sun/solarstorm.md
          - sun/GravityAssist.md
